apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: workerpodautoscaler
  name: workerpodautoscaler
  namespace: kube-system
spec:
  clusterIP: None
  ports:
  - name: workerpodautoscaler-metrics
    port: 8787
    protocol: TCP
    targetPort: 8787
  selector:
    app: workerpodautoscaler
  sessionAffinity: None
  type: ClusterIP
