apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workerpodautoscaler
  labels:
    k8s-app: workerpodautoscaler
  namespace: monitoring
spec:
  jobLabel: k8s-app
  selector:
    matchLabels:
      k8s-app: workerpodautoscaler
  namespaceSelector:
    matchNames:
    - kube-system
  endpoints:
  - port: workerpodautoscaler-metrics
    path: /metrics
    interval: 5s
